### ISSUE TITLE
Yarn build not succeeding in Docker-Compose

### ISSUE THREAD

**Issue by icodesdeveloper** [Eugeny/tabby-web#107]
My frontend yarn build is not succeeding in Docker Compose:
Any idea how to get it working?

`=> ERROR [frontend-build  9/10] RUN yarn run build                                                                                47.0s
------                                                                                                                                   
 > [frontend-build  9/10] RUN yarn run build:                                                                                            
1.412 yarn run v1.22.18                                                                                                                  
1.548 $ webpack --progress                                                                                                               
7.819 <s> [webpack.Progress] 0%                                                                                                          
7.821                                                                                                                                    
7.821 <s> [webpack.Progress] 1% setup initialize                                                                                         
7.822 <s> [webpack.Progress] 1% setup initialize HtmlWebpackPlugin
7.824 <s> [webpack.Progress] 1% setup initialize HtmlWebpackPlugin
7.825 <s> [webpack.Progress] 1% setup initialize HtmlWebpackPlugin
7.826 <s> [webpack.Progress] 1% setup initialize
7.827 <s> [webpack.Progress] 2% setup before run
7.828 <s> [webpack.Progress] 2% setup before run NodeEnvironmentPlugin
7.829 <s> [webpack.Progress] 2% setup before run
7.845 <s> [webpack.Progress] 3% setup run
7.846 <s> [webpack.Progress] 3% setup run webpack-cli
7.846 <s> [webpack.Progress] 3% setup run
7.854 <s> [webpack.Progress] 4% setup normal module factory
7.855 <s> [webpack.Progress] 4% setup normal module factory
7.856 <s> [webpack.Progress] 5% setup context module factory
7.857 <s> [webpack.Progress] 5% setup context module factory
7.858 <s> [webpack.Progress] 6% setup before compile
7.858 <s> [webpack.Progress] 6% setup before compile ProgressPlugin
7.860 <s> [webpack.Progress] 6% setup before compile
7.861 <s> [webpack.Progress] 7% setup compile
7.861 <s> [webpack.Progress] 7% setup compile ExternalsPlugin
7.862 <s> [webpack.Progress] 7% setup compile
7.884 <s> [webpack.Progress] 8% setup compilation
7.884 <s> [webpack.Progress] 8% setup compilation mini-css-extract-plugin
7.886 <s> [webpack.Progress] 8% setup compilation angular-compiler
28.40 Compiling @angular/core : esm2015 as esm2015
28.74 Compiling @angular/animations : esm2015 as esm2015
41.99 Error: Error on worker #2: Error: EINVAL: invalid argument, rename '/app/node_modules/@angular/animations/animations.d.ts' -> '/app/node_modules/@angular/animations/animations.d.ts.__ivy_ngcc_bak'
41.99     at Object.renameSync (fs.js:741:3)
41.99     at NodeJSFileSystem.moveFile (/app/node_modules/@angular/compiler-cli/src/ngtsc/file_system/src/node_js_file_system.js:142:16)
41.99     at NewEntryPointFileWriter.InPlaceFileWriter.writeFileAndBackup (/app/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:72:29)
41.99     at NewEntryPointFileWriter.writeFile (/app/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:128:53)
41.99     at /app/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:47:69
41.99     at Array.forEach (<anonymous>)
41.99     at NewEntryPointFileWriter.writeBundle (/app/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:47:30)
41.99     at writeBundle (/app/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:58:36)
41.99     at processTicksAndRejections (internal/process/task_queues.js:97:5)
41.99     at ClusterMaster.onWorkerMessage (/app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
41.99     at /app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
41.99     at ClusterMaster.<anonymous> (/app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
41.99     at step (/app/node_modules/tslib/tslib.js:143:27)
41.99     at Object.next (/app/node_modules/tslib/tslib.js:124:57)
41.99     at /app/node_modules/tslib/tslib.js:117:75
41.99     at new Promise (<anonymous>)
41.99     at Object.__awaiter (/app/node_modules/tslib/tslib.js:113:16)
41.99     at EventEmitter.<anonymous> (/app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
41.99     at EventEmitter.emit (events.js:314:20)
42.15 [webpack-cli] Error: NGCC failed.
42.15     at NgccProcessor.process (/app/node_modules/@ngtools/webpack/src/ngcc_processor.js:139:19)
42.15     at /app/node_modules/@ngtools/webpack/src/ivy/plugin.js:129:27
42.15     at Hook.eval [as call] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:14:1)
42.15     at Hook.CALL_DELEGATE [as _call] (/app/node_modules/tapable/lib/Hook.js:14:14)
42.15     at Compiler.newCompilation (/app/node_modules/webpack/lib/Compiler.js:1052:30)
42.15     at /app/node_modules/webpack/lib/Compiler.js:1097:29
42.15     at Hook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
42.15     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:18:14)
42.15     at Compiler.compile (/app/node_modules/webpack/lib/Compiler.js:1092:28)
42.15     at /app/node_modules/webpack/lib/Compiler.js:517:12
42.25 error Command failed with exit code 2.
42.29 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:10
--------------------
   8 |     COPY frontend/src src
   9 |     COPY frontend/theme theme
  10 | >>> RUN yarn run build
  11 |     RUN yarn run build:server
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn run build" did not complete successfully: exit code: 2
ERROR: Service 'tabby' failed to build : Build failed
root@tabby:/opt/tabby/tabby-web# `

**Comment by chenzhiguo** [comment]
Any body deploy success?
