### ISSUE TITLE
Improperly configured

### ISSUE THREAD

**Issue by schtinkafinga** [Eugeny/tabby-web#24]
Hello, with a high possibility it's me who didn't configure it correctly. But i can't figure out where did i take a wrong step.

backend logs:
```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```

frontend logs:

```
Node Express server listening on http://localhost:80
Node Express server listening on http://localhost:80
Node Express server listening on http://localhost:80
Node Express server listening on http://localhost:80
http://localhost:9091
ERROR TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'XMLHttpRequest'
    |     property 'upload' -> object with constructor 'XMLHttpRequestUpload'
    --- property '_request' closes the circle
    at JSON.stringify (<anonymous>)
    at readableObjectToString (/app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:1016:1)
    at resolvePromise (/app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:1183:1)
    at resolvePromise (/app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:1137:1)
    at /app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:1249:1
    at ZoneDelegate.invokeTask (/app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:434:1)
    at Object.onInvokeTask (/app/build-server/webpack:/tabby-web/node_modules/@angular/core/__ivy_ngcc__/esm2015/src/zone/ng_zone.js:295:1)
    at ZoneDelegate.invokeTask (/app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:433:1)
    at Zone.runTask (/app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:205:1)
    at drainMicroTaskQueue (/app/build-server/webpack:/tabby-web/node_modules/zone.js/dist/zone-node.js:620:1) {
  rejection: HttpErrorResponse {
    headers: HttpHeaders {
      normalizedNames: Map {},
      lazyUpdate: null,
      headers: Map {}
    },
    status: 0,
    statusText: 'Unknown Error',
    url: 'http://localhost:9091/api/1/instance-info',
    ok: false,
    name: 'HttpErrorResponse',
    message: 'Http failure response for http://localhost:9091/api/1/instance-info: 0 Unknown Error',
    error: ProgressEvent {
      type: 'error',
      target: [XMLHttpRequest],
      currentTarget: [XMLHttpRequest],
      lengthComputable: false,
      loaded: 0,
      total: 0
    }
  },
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: HttpErrorResponse {
      headers: [HttpHeaders],
      status: 0,
      statusText: 'Unknown Error',
      url: 'http://localhost:9091/api/1/instance-info',
      ok: false,
      name: 'HttpErrorResponse',
      message: 'Http failure response for http://localhost:9091/api/1/instance-info: 0 Unknown Error',
      error: [ProgressEvent]
    }
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: [HttpErrorResponse]
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
```
It doesn't work on port 80, but if i go to 9090, it half-works, with the blank black page and following in console:
```
ERROR Error: Uncaught (in promise): u: {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":"http://localhost:9091/api/1/instance-info","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:9091/api/1/instance-info: 0 Unknown Error","error":{"isTrusted":true}}
```

**Comment by Eugeny** [comment]
Hey, you need to supply a `DATABASE_URL` env var for the backend container/process - either directly as an environment variable or in the `.env` file in the repo root. See https://github.com/kennethreitz/dj-database-url for the exact format.

The Docker container will set up the database structure automatically, and if you run it locally, just do a `./manage.py migrate` beforehand.
