### ISSUE TITLE
Paste

### ISSUE THREAD

**Issue by capriciousduck** [Eugeny/tabby-web#36]
Hi @Eugeny 

Right-click and paste is not working. Neither Ctrl + V or Ctrl + Shift + V. What do I do?

**Comment by crotoc** [comment]
I have the same problem and it's sad I couldn't figure out how to do. Then I use wetty instead.

**Comment by brunnels** [comment]
I was wrong.  With both tabby-web and connection gateway behind ssl paste still does not work.

**Comment by brunnels** [comment]
I just verified paste works in the latest app version https://www.npmjs.com/package/tabby-web-container/v/1.0.189-nightly.2

If you're running in a container and have a volume mounted at /app-dist inside the container for your storage you can `docker exec` into the container and do this to add the new version:
```
cd /app
APP_DIST_STORAGE=file:///app-dist /venv/*/bin/python ./manage.py add_version 1.0.189-nightly.2
```

**Comment by crotoc** [comment]
Thanks:)

**Comment by linconbb** [comment]
But I found it doesn't work in 1.0.189.night.2 as well . So I update it to 1.0.197 nightly.1 .  But it stucks in tabby  alpha ProgressBar.

**Comment by alexdelprete** [comment]
> If you're running in a container and have a volume mounted at /app-dist inside the container for your storage you can `docker exec` into the container and do this to add the new version:

Do you have an advice for me regarding this error? I can't install the app (tried several versions) in the container. :(

```console
/app # APP_DIST_STORAGE=file:///app-dist /venv/*/bin/python ./manage.py add_version latest
INFO Resolving tabby-web-container@latest
INFO Downloading tabby-web-container@latest from https://registry.npmjs.org/tabby-web-container/-/tabby-web-container-1.0.197-nightly.1.tgz
INFO Resolving tabby-core@latest
INFO Downloading tabby-core@latest from https://registry.npmjs.org/tabby-core/-/tabby-core-1.0.197-nightly.1.tgz
INFO Resolving tabby-settings@latest
INFO Downloading tabby-settings@latest from https://registry.npmjs.org/tabby-settings/-/tabby-settings-1.0.197-nightly.1.tgz
INFO Resolving tabby-terminal@latest
INFO Downloading tabby-terminal@latest from https://registry.npmjs.org/tabby-terminal/-/tabby-terminal-1.0.197-nightly.1.tgz
INFO Resolving tabby-ssh@latest
INFO Downloading tabby-ssh@latest from https://registry.npmjs.org/tabby-ssh/-/tabby-ssh-1.0.197-nightly.1.tgz
INFO Resolving tabby-community-color-schemes@latest
INFO Downloading tabby-community-color-schemes@latest from https://registry.npmjs.org/tabby-community-color-schemes/-/tabby-community-color-schemes-1.0.197-nightly.1.tgz
tar: invalid magic
tar: short read
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/tabby/app/management/commands/add_version.py", line 56, in handle
    ["tar", "-xzf", f.name, "-C", str(extraction_tmp)]
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xzf', '/tmp/tmp4fvs37f6', '-C', '/tmp/tmpwycziuo2']' returned non-zero exit status 1.
```

**Comment by gxt-kt** [comment]
I found the resolution in windows.
Just remove the paste shortcuts `ctrl+shift+v` in setting. And you can use ctrl+shift+v to paste.
If you use macos, you don't need to set anything because mac use command+v to paste.

**Comment by LeonvanHeerden** [comment]
> I found the resolution in windows. Just remove the paste shortcuts `ctrl+shift+v` in setting. And you can use ctrl+shift+v to paste. If you use macos, you don't need to set anything because mac use command+v to paste.

Thank you this resolved my issue.
