### ISSUE TITLE
ARM64 - Not working

### ISSUE THREAD

**Issue by MaxWaldorf** [Eugeny/tabby-web#44]
continuing #43 

```

/usr/local/bin/dockerize: line 1: syntax error: unexpected word (expecting ")")
--
Thu, Jan 27 2022 1:20:12 pm | Traceback (most recent call last):
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Thu, Jan 27 2022 1:20:12 pm | self.connect()
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 33, in inner
Thu, Jan 27 2022 1:20:12 pm | return func(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 200, in connect
Thu, Jan 27 2022 1:20:12 pm | self.connection = self.get_new_connection(conn_params)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 33, in inner
Thu, Jan 27 2022 1:20:12 pm | return func(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
Thu, Jan 27 2022 1:20:12 pm | connection = Database.connect(**conn_params)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/MySQLdb/__init__.py", line 130, in Connect
Thu, Jan 27 2022 1:20:12 pm | return Connection(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
Thu, Jan 27 2022 1:20:12 pm | super().__init__(*args, **kwargs2)
Thu, Jan 27 2022 1:20:12 pm | MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")
Thu, Jan 27 2022 1:20:12 pm |  
Thu, Jan 27 2022 1:20:12 pm | The above exception was the direct cause of the following exception:
Thu, Jan 27 2022 1:20:12 pm |  
Thu, Jan 27 2022 1:20:12 pm | Traceback (most recent call last):
Thu, Jan 27 2022 1:20:12 pm | File "./manage.py", line 22, in <module>
Thu, Jan 27 2022 1:20:12 pm | main()
Thu, Jan 27 2022 1:20:12 pm | File "./manage.py", line 18, in main
Thu, Jan 27 2022 1:20:12 pm | execute_from_command_line(sys.argv)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
Thu, Jan 27 2022 1:20:12 pm | utility.execute()
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
Thu, Jan 27 2022 1:20:12 pm | self.fetch_command(subcommand).run_from_argv(self.argv)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
Thu, Jan 27 2022 1:20:12 pm | self.execute(*args, **cmd_options)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
Thu, Jan 27 2022 1:20:12 pm | output = self.handle(*args, **options)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
Thu, Jan 27 2022 1:20:12 pm | res = handle_func(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 75, in handle
Thu, Jan 27 2022 1:20:12 pm | self.check(databases=[database])
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 423, in check
Thu, Jan 27 2022 1:20:12 pm | databases=databases,
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/checks/registry.py", line 76, in run_checks
Thu, Jan 27 2022 1:20:12 pm | new_errors = check(app_configs=app_configs, databases=databases)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/checks/database.py", line 13, in check_database_backends
Thu, Jan 27 2022 1:20:12 pm | issues.extend(conn.validation.check(**kwargs))
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/mysql/validation.py", line 9, in check
Thu, Jan 27 2022 1:20:12 pm | issues.extend(self._check_sql_mode(**kwargs))
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
Thu, Jan 27 2022 1:20:12 pm | if not (self.connection.sql_mode & {'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES'}):
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
Thu, Jan 27 2022 1:20:12 pm | res = instance.__dict__[self.name] = self.func(instance)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 405, in sql_mode
Thu, Jan 27 2022 1:20:12 pm | sql_mode = self.mysql_server_data['sql_mode']
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
Thu, Jan 27 2022 1:20:12 pm | res = instance.__dict__[self.name] = self.func(instance)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 366, in mysql_server_data
Thu, Jan 27 2022 1:20:12 pm | with self.temporary_connection() as cursor:
Thu, Jan 27 2022 1:20:12 pm | File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
Thu, Jan 27 2022 1:20:12 pm | return next(self.gen)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
Thu, Jan 27 2022 1:20:12 pm | with self.cursor() as cursor:
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 33, in inner
Thu, Jan 27 2022 1:20:12 pm | return func(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 259, in cursor
Thu, Jan 27 2022 1:20:12 pm | return self._cursor()
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 235, in _cursor
Thu, Jan 27 2022 1:20:12 pm | self.ensure_connection()
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 33, in inner
Thu, Jan 27 2022 1:20:12 pm | return func(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Thu, Jan 27 2022 1:20:12 pm | self.connect()
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
Thu, Jan 27 2022 1:20:12 pm | raise dj_exc_value.with_traceback(traceback) from exc_value
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Thu, Jan 27 2022 1:20:12 pm | self.connect()
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 33, in inner
Thu, Jan 27 2022 1:20:12 pm | return func(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 200, in connect
Thu, Jan 27 2022 1:20:12 pm | self.connection = self.get_new_connection(conn_params)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 33, in inner
Thu, Jan 27 2022 1:20:12 pm | return func(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
Thu, Jan 27 2022 1:20:12 pm | connection = Database.connect(**conn_params)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/MySQLdb/__init__.py", line 130, in Connect
Thu, Jan 27 2022 1:20:12 pm | return Connection(*args, **kwargs)
Thu, Jan 27 2022 1:20:12 pm | File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
Thu, Jan 27 2022 1:20:12 pm | super().__init__(*args, **kwargs2)
Thu, Jan 27 2022 1:20:12 pm | django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")
Thu, Jan 27 2022 1:20:15 pm | [2022-01-27 12:20:15 +0000] [9] [INFO] Starting gunicorn 20.1.0
Thu, Jan 27 2022 1:20:15 pm | [2022-01-27 12:20:15 +0000] [9] [INFO] Listening at: http://0.0.0.0:80 (9)
Thu, Jan 27 2022 1:20:15 pm | [2022-01-27 12:20:15 +0000] [9] [INFO] Using worker: sync
Thu, Jan 27 2022 1:20:15 pm | [2022-01-27 12:20:15 +0000] [11] [INFO] Booting worker with pid: 11
Thu, Jan 27 2022 1:20:15 pm | [2022-01-27 12:20:15 +0000] [12] [INFO] Booting worker with pid: 12
Thu, Jan 27 2022 1:20:15 pm | [2022-01-27 12:20:15 +0000] [13] [INFO] Booting worker with pid: 13
Thu, Jan 27 2022 1:20:15 pm | [2022-01-27 12:20:15 +0000] [14] [INFO] Booting worker with pid: 14

```

**Comment by Eugeny** [comment]
Found a broken variable check, but I'm not sure that's it. `/usr/local/bin/dockerize: line 1: syntax error: unexpected word (expecting ")")` looks like it might be interpreting the dockerize binary as a shell script for some reason?!

P.S. Is there any easy way for me to test the image without access to arm64 hardware?

**Comment by MaxWaldorf** [comment]
Sure, you can emulate ARM64 in x64 hardware thanks to QEMU.
(exactly the same principle as the pipeline I updated for both repos)

You can inspire yourself from [this article](https://wiki.ubuntu.com/ARM64/QEMU).

I did it in the past on windows 10 and it worked great (but slightly slow)...

**Comment by MaxWaldorf** [comment]
Last build still failing but I think you need to investigate a bit more.

Let me know if I can help with my limited knowledge...
