### ISSUE TITLE
Unable to use Postgres DB

### ISSUE THREAD

**Issue by zachstence** [Eugeny/tabby-web#79]
When trying to self host Tabby (including TCG, web, and a postgres DB), I get an error regarding `psycopg2`

## Reproduction steps
1. Create `docker-compose.yml` with the following contents
```yml
version: '3'

services:
  tcg:
    image: ghcr.io/eugeny/tabby-connection-gateway:master
    environment:
      TABBY_AUTH_TOKEN: tabby_auth_token
    command: --token-auth --host 0.0.0.0

  db:
    image: postgres:13.4
    environment:
      PGDATA: /var/lib/postgresql/data/tabby
      POSTGRES_DB: tabby
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: tabby_web

  web:
    image: ghcr.io/eugeny/tabby-web:master
    depends_on:
      - db
      - tcg
    environment:
      DATABASE_URL: 'postgresql://tabby_web:password123@db/tabby'
```

2. Run `docker compose up`
3. Observe the error
```txt
tabby-web-1  | Traceback (most recent call last):
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
tabby-web-1  |     import psycopg2 as Database
tabby-web-1  | ModuleNotFoundError: No module named 'psycopg2'
tabby-web-1  | 
tabby-web-1  | During handling of the above exception, another exception occurred:
tabby-web-1  | 
tabby-web-1  | Traceback (most recent call last):
tabby-web-1  |   File "./manage.py", line 22, in <module>
tabby-web-1  |     main()
tabby-web-1  |   File "./manage.py", line 18, in main
tabby-web-1  |     execute_from_command_line(sys.argv)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
tabby-web-1  |     utility.execute()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
tabby-web-1  |     django.setup()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
tabby-web-1  |     apps.populate(settings.INSTALLED_APPS)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
tabby-web-1  |     app_config.import_models()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/apps/config.py", line 301, in import_models
tabby-web-1  |     self.models_module = import_module(models_module_name)
tabby-web-1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
tabby-web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
tabby-web-1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/contrib/auth/models.py", line 3, in <module>
tabby-web-1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
tabby-web-1  |     class AbstractBaseUser(models.Model):
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/models/base.py", line 122, in __new__
tabby-web-1  |     new_class.add_to_class('_meta', Options(meta, app_label))
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/models/base.py", line 326, in add_to_class
tabby-web-1  |     value.contribute_to_class(cls, name)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/models/options.py", line 207, in contribute_to_class
tabby-web-1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/connection.py", line 15, in __getattr__
tabby-web-1  |     return getattr(self._connections[self._alias], item)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/connection.py", line 62, in __getitem__
tabby-web-1  |     conn = self.create_connection(alias)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 204, in create_connection
tabby-web-1  |     backend = load_backend(db['ENGINE'])
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 111, in load_backend
tabby-web-1  |     return import_module('%s.base' % backend_name)
tabby-web-1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
tabby-web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
tabby-web-1  |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
tabby-web-1  | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
tabby-web-1  | Traceback (most recent call last):
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
tabby-web-1  |     import psycopg2 as Database
tabby-web-1  | ModuleNotFoundError: No module named 'psycopg2'
tabby-web-1  | 
tabby-web-1  | During handling of the above exception, another exception occurred:
tabby-web-1  | 
tabby-web-1  | Traceback (most recent call last):
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/bin/gunicorn", line 8, in <module>
tabby-web-1  |     sys.exit(run())
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
tabby-web-1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/app/base.py", line 231, in run
tabby-web-1  |     super().run()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
tabby-web-1  |     Arbiter(self).run()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/arbiter.py", line 58, in __init__
tabby-web-1  |     self.setup(app)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/arbiter.py", line 118, in setup
tabby-web-1  |     self.app.wsgi()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
tabby-web-1  |     self.callable = self.load()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
tabby-web-1  |     return self.load_wsgiapp()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
tabby-web-1  |     return util.import_app(self.app_uri)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
tabby-web-1  |     mod = importlib.import_module(module)
tabby-web-1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
tabby-web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
tabby-web-1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
tabby-web-1  |   File "/app/tabby/wsgi.py", line 7, in <module>
tabby-web-1  |     application = get_wsgi_application()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
tabby-web-1  |     django.setup(set_prefix=False)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
tabby-web-1  |     apps.populate(settings.INSTALLED_APPS)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
tabby-web-1  |     app_config.import_models()
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/apps/config.py", line 301, in import_models
tabby-web-1  |     self.models_module = import_module(models_module_name)
tabby-web-1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
tabby-web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
tabby-web-1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
tabby-web-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/contrib/auth/models.py", line 3, in <module>
tabby-web-1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
tabby-web-1  |     class AbstractBaseUser(models.Model):
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/models/base.py", line 122, in __new__
tabby-web-1  |     new_class.add_to_class('_meta', Options(meta, app_label))
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/models/base.py", line 326, in add_to_class
tabby-web-1  |     value.contribute_to_class(cls, name)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/models/options.py", line 207, in contribute_to_class
tabby-web-1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/connection.py", line 15, in __getattr__
tabby-web-1  |     return getattr(self._connections[self._alias], item)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/utils/connection.py", line 62, in __getitem__
tabby-web-1  |     conn = self.create_connection(alias)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 204, in create_connection
tabby-web-1  |     backend = load_backend(db['ENGINE'])
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 111, in load_backend
tabby-web-1  |     return import_module('%s.base' % backend_name)
tabby-web-1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
tabby-web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
tabby-web-1  |   File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
tabby-web-1  |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
tabby-web-1  | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
```

**Comment by varoOP** [comment]
The image doesn't have the driver to connect to postgre. Either try using mariaDB or rebuild image with psycopg2 installed.
