### ISSUE TITLE
failed to deploy on remote server

### ISSUE THREAD

**Issue by sagerenn** [Eugeny/tabby-web#86]
![image](https://user-images.githubusercontent.com/49195270/215267642-ebe181ab-c316-4e09-b801-91cca7328f11.png)

cannot find the js:
```
http://xxxxx/app-dist/1.0.163/tabby-web-container/dist/preload.js
http://xxxxx/app-dist/1.0.163/tabby-web-container/dist/bundle.js
```

running cmd:
```
docker run -d --name tabby      -e DATABASE_URL=sqlite:////app-dist/database.sqlite3   -p 30000:80   -e PORT=80 -e DEBUG=True -e APP_DIST_STORAGE=file:///app-dist -e ENABLE_HOMEPAGE=False  -e SOCIAL_AUTH_GITHUB_KEY=xxxxx -e SOCIAL_AUTH_GITHUB_SECRET=xxxxx    ghcr.io/eugeny/tabby-web:master sh -c "/manage.sh add_version 1.0.163 && cd /app && /start.sh"
```

**Comment by huzheyi** [comment]
> SOCIAL_AUTH_GITHUB_SECRET

it seems the npm packet is unpacked to a folder with a temp name, like:
````
1.0.163
  - tmpfolder
     - tabby-web-container
     - ...
````
so just look into /app-dist to fix the folder name

**Comment by archibaldodlc** [comment]
I had the same problem and I resolved doing this:

I'm using this version: 1.0.189-nightly.2 (with the latest one don't work for me)

- Go inside the container: 

`
docker exec -it tabby-web-container /bin/sh
`

- Install version 1.0.189-nightly.2
`
/manage.sh add_version 1.0.189-nightly.2
`

- CD to version folder: 
`
cd /app-dist/1.0.189-nightly.2
`

- Move all content from tmp folder to current folder (/app-dist/1.0.189-nightly.2/):
`
mv tmpfolder/* ./
`

Remove the tmp folder
`
rm -rf tmpfolder
`

Refresh the page on Tabby Web and select the version installed.

Hope it helps.

**Comment by alexdelprete** [comment]
> I had the same problem and I resolved doing this:

I have this issue and can't solve it, tried with any version of the image (the old master and latest nightly) and with several app versions:

```console
❯ docker compose run tabby-web /manage.sh add_version 1.0.189-nightly.2
[+] Creating 1/0                                                                                                                                                                                                      
INFO Resolving tabby-web-container@1.0.189-nightly.2
INFO Downloading tabby-web-container@1.0.189-nightly.2 from https://registry.npmjs.org/tabby-web-container/-/tabby-web-container-1.0.189-nightly.2.tgz
INFO Resolving tabby-core@1.0.189-nightly.2
INFO Downloading tabby-core@1.0.189-nightly.2 from https://registry.npmjs.org/tabby-core/-/tabby-core-1.0.189-nightly.2.tgz
INFO Resolving tabby-settings@1.0.189-nightly.2
INFO Downloading tabby-settings@1.0.189-nightly.2 from https://registry.npmjs.org/tabby-settings/-/tabby-settings-1.0.189-nightly.2.tgz
INFO Resolving tabby-terminal@1.0.189-nightly.2
INFO Downloading tabby-terminal@1.0.189-nightly.2 from https://registry.npmjs.org/tabby-terminal/-/tabby-terminal-1.0.189-nightly.2.tgz
INFO Resolving tabby-ssh@1.0.189-nightly.2
INFO Downloading tabby-ssh@1.0.189-nightly.2 from https://registry.npmjs.org/tabby-ssh/-/tabby-ssh-1.0.189-nightly.2.tgz
INFO Resolving tabby-community-color-schemes@1.0.189-nightly.2
INFO Downloading tabby-community-color-schemes@1.0.189-nightly.2 from https://registry.npmjs.org/tabby-community-color-schemes/-/tabby-community-color-schemes-1.0.189-nightly.2.tgz
tar: invalid magic
tar: short read
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/tabby/app/management/commands/add_version.py", line 56, in handle
    ["tar", "-xzf", f.name, "-C", str(extraction_tmp)]
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xzf', '/tmp/tmptiijiy6h', '-C', '/tmp/tmp6pyit54s']' returned non-zero exit status 1.
```

**Comment by Dima-Kal** [comment]
> I had the same problem and I resolved doing this:
> 
> I'm using this version: 1.0.189-nightly.2 (with the latest one don't work for me)
> 
> * Go inside the container:
>   `docker exec -it tabby-web-container /bin/sh`
> * Install version 1.0.189-nightly.2
>   `/manage.sh add_version 1.0.189-nightly.2`
> * CD to version folder:
>   `cd /app-dist/1.0.189-nightly.2`
> * Move all content from tmp folder to current folder (/app-dist/1.0.189-nightly.2/):
>   `mv tmpfolder/* ./`
> * Remove the tmp folder
>   `rm -rf tmpfolder`
> 
> Refresh the page on Tabby Web and select the version installed.
> 
> Hope it helps.

Worked for me, why this issue still exists for more than 6 months?
